import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

function nav(){
return (
<nav className="flex items-center justify between border-b p-4 text-xl font-semibold">
  <a href="/gallery" className="cursor-pointer">Gallery</a>
  <a href="/signnup" className="cursor-pointer">Sign up
  </a>
</nav>


);

}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
      <nav />
        {children}</body>
    </html>
  );
}
